// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168
#pragma warning disable CS1591 // document public APIs

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Formatters.Descriptions.Units
{
    public sealed class UnitDescriptionFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Descriptions.Units.UnitDescription>
    {
        // Prefab
        private static global::System.ReadOnlySpan<byte> GetSpan_Prefab() => new byte[1 + 6] { 166, 80, 114, 101, 102, 97, 98 };
        // MoveSpeed
        private static global::System.ReadOnlySpan<byte> GetSpan_MoveSpeed() => new byte[1 + 9] { 169, 77, 111, 118, 101, 83, 112, 101, 101, 100 };
        // BaseDamage
        private static global::System.ReadOnlySpan<byte> GetSpan_BaseDamage() => new byte[1 + 10] { 170, 66, 97, 115, 101, 68, 97, 109, 97, 103, 101 };
        // BaseHealth
        private static global::System.ReadOnlySpan<byte> GetSpan_BaseHealth() => new byte[1 + 10] { 170, 66, 97, 115, 101, 72, 101, 97, 108, 116, 104 };
        // AttackType
        private static global::System.ReadOnlySpan<byte> GetSpan_AttackType() => new byte[1 + 10] { 170, 65, 116, 116, 97, 99, 107, 84, 121, 112, 101 };
        // Id
        private static global::System.ReadOnlySpan<byte> GetSpan_Id() => new byte[1 + 2] { 162, 73, 100 };

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::Descriptions.Units.UnitDescription value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value is null)
            {
                writer.WriteNil();
                return;
            }

            var formatterResolver = options.Resolver;
            writer.WriteMapHeader(6);
            writer.WriteRaw(GetSpan_Prefab());
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Descriptions.Types.AddressableAsset<global::UnityEngine.GameObject>>(formatterResolver).Serialize(ref writer, value.Prefab, options);
            writer.WriteRaw(GetSpan_MoveSpeed());
            writer.Write(value.MoveSpeed);
            writer.WriteRaw(GetSpan_BaseDamage());
            writer.Write(value.BaseDamage);
            writer.WriteRaw(GetSpan_BaseHealth());
            writer.Write(value.BaseHealth);
            writer.WriteRaw(GetSpan_AttackType());
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Descriptions.Units.BaseAttackType>(formatterResolver).Serialize(ref writer, value.AttackType, options);
            writer.WriteRaw(GetSpan_Id());
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.Id, options);
        }

        public global::Descriptions.Units.UnitDescription Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            var formatterResolver = options.Resolver;
            var length = reader.ReadMapHeader();
            var ____result = new global::Descriptions.Units.UnitDescription();

            for (int i = 0; i < length; i++)
            {
                var stringKey = global::MessagePack.Internal.CodeGenHelpers.ReadStringSpan(ref reader);
                switch (stringKey.Length)
                {
                    default:
                    FAIL:
                      reader.Skip();
                      continue;
                    case 6:
                        if (global::MessagePack.Internal.AutomataKeyGen.GetKey(ref stringKey) != 108170469274192UL) { goto FAIL; }

                        ____result.Prefab = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Descriptions.Types.AddressableAsset<global::UnityEngine.GameObject>>(formatterResolver).Deserialize(ref reader, options);
                        continue;
                    case 9:
                        if (!global::System.MemoryExtensions.SequenceEqual(stringKey, GetSpan_MoveSpeed().Slice(1))) { goto FAIL; }

                        ____result.MoveSpeed = reader.ReadSingle();
                        continue;
                    case 10:
                        switch (global::MessagePack.Internal.AutomataKeyGen.GetKey(ref stringKey))
                        {
                            default: goto FAIL;
                            case 7020374340528202050UL:
                                if (global::MessagePack.Internal.AutomataKeyGen.GetKey(ref stringKey) != 25959UL) { goto FAIL; }

                                ____result.BaseDamage = reader.ReadSingle();
                                continue;

                            case 7809634590451261762UL:
                                if (global::MessagePack.Internal.AutomataKeyGen.GetKey(ref stringKey) != 26740UL) { goto FAIL; }

                                ____result.BaseHealth = reader.ReadSingle();
                                continue;

                            case 8742730851213931585UL:
                                if (global::MessagePack.Internal.AutomataKeyGen.GetKey(ref stringKey) != 25968UL) { goto FAIL; }

                                ____result.AttackType = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::Descriptions.Units.BaseAttackType>(formatterResolver).Deserialize(ref reader, options);
                                continue;

                        }
                    case 2:
                        if (global::MessagePack.Internal.AutomataKeyGen.GetKey(ref stringKey) != 25673UL) { goto FAIL; }

                        ____result.Id = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        continue;

                }
            }

            reader.Depth--;
            return ____result;
        }
    }

}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1129 // Do not use default value type constructor
#pragma warning restore SA1309 // Field names should not begin with underscore
#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name
