// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168
#pragma warning disable CS1591 // document public APIs

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Formatters.Descriptions.Main
{
    public sealed class AppearanceDescriptionFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Descriptions.Main.AppearanceDescription>
    {
        // HairsCount
        private static global::System.ReadOnlySpan<byte> GetSpan_HairsCount() => new byte[1 + 10] { 170, 72, 97, 105, 114, 115, 67, 111, 117, 110, 116 };
        // EyesCount
        private static global::System.ReadOnlySpan<byte> GetSpan_EyesCount() => new byte[1 + 9] { 169, 69, 121, 101, 115, 67, 111, 117, 110, 116 };
        // HairColors
        private static global::System.ReadOnlySpan<byte> GetSpan_HairColors() => new byte[1 + 10] { 170, 72, 97, 105, 114, 67, 111, 108, 111, 114, 115 };
        // Id
        private static global::System.ReadOnlySpan<byte> GetSpan_Id() => new byte[1 + 2] { 162, 73, 100 };

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::Descriptions.Main.AppearanceDescription value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value is null)
            {
                writer.WriteNil();
                return;
            }

            var formatterResolver = options.Resolver;
            writer.WriteMapHeader(4);
            writer.WriteRaw(GetSpan_HairsCount());
            writer.Write(value.HairsCount);
            writer.WriteRaw(GetSpan_EyesCount());
            writer.Write(value.EyesCount);
            writer.WriteRaw(GetSpan_HairColors());
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::UnityEngine.Color[]>(formatterResolver).Serialize(ref writer, value.HairColors, options);
            writer.WriteRaw(GetSpan_Id());
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.Id, options);
        }

        public global::Descriptions.Main.AppearanceDescription Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            var formatterResolver = options.Resolver;
            var length = reader.ReadMapHeader();
            var ____result = new global::Descriptions.Main.AppearanceDescription();

            for (int i = 0; i < length; i++)
            {
                var stringKey = global::MessagePack.Internal.CodeGenHelpers.ReadStringSpan(ref reader);
                switch (stringKey.Length)
                {
                    default:
                    FAIL:
                      reader.Skip();
                      continue;
                    case 10:
                        switch (global::MessagePack.Internal.AutomataKeyGen.GetKey(ref stringKey))
                        {
                            default: goto FAIL;
                            case 8462056387972260168UL:
                                if (global::MessagePack.Internal.AutomataKeyGen.GetKey(ref stringKey) != 29806UL) { goto FAIL; }

                                ____result.HairsCount = reader.ReadInt32();
                                continue;

                            case 8028914571167752520UL:
                                if (global::MessagePack.Internal.AutomataKeyGen.GetKey(ref stringKey) != 29554UL) { goto FAIL; }

                                ____result.HairColors = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::UnityEngine.Color[]>(formatterResolver).Deserialize(ref reader, options);
                                continue;

                        }
                    case 9:
                        if (!global::System.MemoryExtensions.SequenceEqual(stringKey, GetSpan_EyesCount().Slice(1))) { goto FAIL; }

                        ____result.EyesCount = reader.ReadInt32();
                        continue;
                    case 2:
                        if (global::MessagePack.Internal.AutomataKeyGen.GetKey(ref stringKey) != 25673UL) { goto FAIL; }

                        ____result.Id = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        continue;

                }
            }

            reader.Depth--;
            return ____result;
        }
    }

}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1129 // Do not use default value type constructor
#pragma warning restore SA1309 // Field names should not begin with underscore
#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name
